controller_list:
  - name: fake_arm_group_controller
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_eff_group_controller
    joints:
      []